POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "teste",
    "email": "email@email.com",
    "password": "23432535"
}

###
GET http://localhost:3003/user/

###
POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "title": "teste",
    "durationInMinutes": 120,
    "yearOfRElease": 2020,
    "description": "testando endpoint"
}

